version: "3.9"

services: 
    backend:
        container_name: backend
        build: 
            context: ./backend/
            dockerfile: Dockerfile
        restart: always
    nginx:
        depends_on: 
            - backend
        container_name: proxy
        build: 
            context: ./src/frontend/
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        restart: always