version: "3.9"

services: 
    backend:
        container_name: backend
        build: 
            context: ./src/backend/
            dockerfile: Dockerfile
        restart: always
    
    # nginx:
    #     container_name: proxy
    #     build: ./nginx
    #     depends_on: 
    #         - backend
    #     ports: 
    #         - "80:80"
    #     restart: always