version: "3.9"

services:
    database:
        image: postgres:14.5
        container_name: solution_database
        env_file:
            - database.env
        volumes:
            - /home/database-data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        restart: always
    
    backend:
        container_name: solution_backend
        depends_on:
            - database
        build: 
            context: ./src/backend/
            dockerfile: Dockerfile
        command: bash -c "cd /app && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        ports:
            - "8000:8000"
        restart: always
    
    frontend:
        container_name: solution_frontend
        depends_on:
            - backend
        build: 
            context: ./src/frontend/
            dockerfile: Dockerfile
        ports:
            - "80:80"
        restart: always
    
    bpm:
        image: camunda/camunda-bpm-platform:latest 
        container_name: bpm
        depends_on:
            - backend
        ports:
            - "8080:8080"
        restart: always

volumes:
    database-data:
    