version: "3.9"

services:

    # Service: Data base Keycloak
    db_keycloak:
        image: postgres:14.5
        container_name: keycloak_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: keycloak            
        volumes:
            - ./database-data-keycloak:/var/lib/postgresql/data/
        ports:
            - "1521:5432"
        restart: always


    # Service: application Keycloak
    app_keycloak:        
        container_name: keycloak_app
        environment:
            DB_URL: http://db_keycloak
            DB_PORT: 1521
            DB: keycloak            
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
            # for dev, for productive change to actual
            HOSTNAME: localhost            
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        volumes:            
            - ./src/keycloak/import:/opt/keycloak/data/import            
        depends_on:
            - db_keycloak
        build: 
            context: ./src/keycloak/
            dockerfile: Dockerfile
        ports:
            - "3443:8443"
            - "3080:8080"
        restart: always
        # override entrypoint for import settings Realm Sovkombank
        #entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]
        entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev", "--import-realm"]    

        
    database:
        image: postgres:14.5
        container_name: solution_database
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres        
        volumes:
            - ./database-data-backend:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        restart: always
    
    backend:
        container_name: solution_backend
        depends_on:
            - database
            - app_keycloak
        environment:            
            KEYCLOAK_URL: http://app_keycloak:8080
            KEYCLOAK_CLIENT_ID: sovkombank
            KEYCLOAK_REALM_NAME: sovkombank
        build: 
            context: ./src/backend/
            dockerfile: Dockerfile
        command: bash -c "cd /app && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        ports:
            - "8000:8000"
        restart: always
   
    frontend:
        container_name: solution_frontend
        depends_on:
            - backend
        build: 
            context: ./src/frontend/
            dockerfile: Dockerfile
        ports:
            - "80:80"
        restart: always   

    database_camunda:
        image: postgres:14.5
        container_name: camunda_database
        environment:
            POSTGRES_USER: camunda
            POSTGRES_PASSWORD: camunda
            POSTGRES_DB: camunda
        volumes:
            - ./database-data-camunda:/var/lib/postgresql/data/
        ports:
            - "1522:5432"
        restart: always        
    
    bpm:
        #image: camunda/camunda-bpm-platform:latest 
        container_name: bpm
        environment:
            DB_DRIVER: org.postgresql.Driver
            DB_URL: jdbc:postgresql://database_camunda:5432/camunda
            DB_USERNAME: camunda
            DB_PASSWORD: camunda            
        build: 
            context: ./src/camunda/        
        depends_on:
            - database_camunda
        ports:
            - "8080:8080"
        restart: always