"""01_initial

Revision ID: 099b72f8d24d
Revises: 
Create Date: 2023-04-15 19:51:05.104267

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '099b72f8d24d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('role_name')
    )
    op.create_table('users',
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_table('role_model',
    sa.Column('user_email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_name'], ['roles.role_name'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_model')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
